/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import FeePaymentContractArtifactJson from "../../../target/fee_payment_contract-FeePayment.json" with { type: "json" };
export const FeePaymentContractArtifact = loadContractArtifact(
  FeePaymentContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract FeePayment;
 */
export class FeePaymentContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, FeePaymentContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, wallet: Wallet): FeePaymentContract {
    return Contract.at(
      address,
      FeePaymentContract.artifact,
      wallet,
    ) as FeePaymentContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<FeePaymentContract>(
      PublicKeys.default(),
      wallet,
      FeePaymentContractArtifact,
      (instance, wallet) => FeePaymentContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet) {
    return new DeployMethod<FeePaymentContract>(
      publicKeys,
      wallet,
      FeePaymentContractArtifact,
      (instance, wallet) => FeePaymentContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof FeePaymentContract["methods"]>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<FeePaymentContract["methods"][M]>
  ) {
    return new DeployMethod<FeePaymentContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      FeePaymentContractArtifact,
      (instance, wallet) => FeePaymentContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return FeePaymentContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      FeePaymentContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<"fee_juice_balance"> {
    return {
      fee_juice_balance: {
        slot: new Fr(1n),
      },
    } as ContractStorageLayout<"fee_juice_balance">;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** get_fee_juice_balance(account: struct) */
    get_fee_juice_balance: ((
      account: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** mint_fee_juice(account: struct, amount: integer) */
    mint_fee_juice: ((
      account: AztecAddressLike,
      amount: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sponsor_for_class_id(expected_class_id: struct) */
    sponsor_for_class_id: ((
      expected_class_id: WrappedFieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sponsor_metered() */
    sponsor_metered: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sponsor_metered_exact() */
    sponsor_metered_exact: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sponsor_metered_teardown_revert() */
    sponsor_metered_teardown_revert: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sponsor_metered_token(token_address: struct, nonce: field) */
    sponsor_metered_token: ((
      token_address: AztecAddressLike,
      nonce: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sponsor_metered_token_exact(token_address: struct, nonce: field) */
    sponsor_metered_token_exact: ((
      token_address: AztecAddressLike,
      nonce: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sponsor_metered_token_teardown_revert(token_address: struct, nonce: field) */
    sponsor_metered_token_teardown_revert: ((
      token_address: AztecAddressLike,
      nonce: FieldLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sponsor_unconditionally() */
    sponsor_unconditionally: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sponsor_unconditionally_teardown_revert() */
    sponsor_unconditionally_teardown_revert: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
