// Re-export the FeePayment contract artifact and type-safe wrapper
// These files are auto-generated by `aztec codegen`
export {
  FeePaymentContract,
  FeePaymentContractArtifact,
} from "./FeePayment.js";
