/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import MeteredContractArtifactJson from "../../../target/metered_contract-Metered.json" with { type: "json" };
export const MeteredContractArtifact = loadContractArtifact(
  MeteredContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract Metered;
 */
export class MeteredContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, MeteredContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, wallet: Wallet): MeteredContract {
    return Contract.at(
      address,
      MeteredContract.artifact,
      wallet,
    ) as MeteredContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet) {
    return new DeployMethod<MeteredContract>(
      PublicKeys.default(),
      wallet,
      MeteredContractArtifact,
      (instance, wallet) => MeteredContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet) {
    return new DeployMethod<MeteredContract>(
      publicKeys,
      wallet,
      MeteredContractArtifact,
      (instance, wallet) => MeteredContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MeteredContract["methods"]>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MeteredContract["methods"][M]>
  ) {
    return new DeployMethod<MeteredContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MeteredContractArtifact,
      (instance, wallet) => MeteredContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MeteredContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      MeteredContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<"balances"> {
    return {
      balances: {
        slot: new Fr(1n),
      },
    } as ContractStorageLayout<"balances">;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** balance_of(account: struct) */
    balance_of: ((account: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** mint(account: struct, amount: integer) */
    mint: ((
      account: AztecAddressLike,
      amount: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** pay_fee() */
    pay_fee: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** pay_fee_exact() */
    pay_fee_exact: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
