/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import MeteredTokenContractArtifactJson from "../../../target/metered_token_contract-MeteredToken.json" with { type: "json" };
export const MeteredTokenContractArtifact = loadContractArtifact(
  MeteredTokenContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract MeteredToken;
 */
export class MeteredTokenContract extends ContractBase {
  private constructor(address: AztecAddress, wallet: Wallet) {
    super(address, MeteredTokenContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): MeteredTokenContract {
    return Contract.at(
      address,
      MeteredTokenContract.artifact,
      wallet,
    ) as MeteredTokenContract;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, token_address: AztecAddressLike) {
    return new DeployMethod<MeteredTokenContract>(
      PublicKeys.default(),
      wallet,
      MeteredTokenContractArtifact,
      (instance, wallet) => MeteredTokenContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    token_address: AztecAddressLike,
  ) {
    return new DeployMethod<MeteredTokenContract>(
      publicKeys,
      wallet,
      MeteredTokenContractArtifact,
      (instance, wallet) => MeteredTokenContract.at(instance.address, wallet),
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MeteredTokenContract["methods"]>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MeteredTokenContract["methods"][M]>
  ) {
    return new DeployMethod<MeteredTokenContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MeteredTokenContractArtifact,
      (instance, wallet) => MeteredTokenContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MeteredTokenContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      MeteredTokenContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<"token"> {
    return {
      token: {
        slot: new Fr(1n),
      },
    } as ContractStorageLayout<"token">;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** constructor(token_address: struct) */
    constructor: ((
      token_address: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_token() */
    get_token: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** pay_fee(nonce: field) */
    pay_fee: ((nonce: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** pay_fee_exact(nonce: field) */
    pay_fee_exact: ((nonce: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
